### ISSUE TITLE
Bakeoff graph format not well enough explained

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/hgvm#134]
In light of recent problems with curoverse paths (which, granted, seem to stem from an internal problem), it does seem to be pretty tough to understand the SQL format just by looking at the bakeoff page and its links.  Would be nice to have better description of coordinate system and especially allelePathItems more readily available to avoid future confusion

https://github.com/ga4gh/schemas/wiki/Human-Genome-Variation-Reference-(HGVR)-Pilot-Project#graph-format

**Comment by macieksmuga** [comment]
The specific problem that kicked off this issue was due to a mis-formatting of the data that I now fixed, but I agree that the coordinate system needs to be better documented in this case.

There are two possible interpretations of 

```
CREATE TABLE AllelePathItem (alleleID INTEGER REFERENCES allele(ID), 
    pathItemIndex INTEGER NOT NULL, -- zero-based index of this pathItem within the entire path
    sequenceID INTEGER NOT NULL REFERENCES Sequence(ID), 
    start INTEGER NOT NULL,
    length INTEGER NOT NULL, 
    strandIsForward BOOLEAN NOT NULL,
    PRIMARY KEY(alleleID, pathItemIndex));
```

in the case that `strandIsForward` is `FALSE`:

The first (and in my opinion "correct") is that a reverse reading begins at the `start` position and proceeds with the reverse complement going left from there. The other is that the `start` and `length` together specify a region on the positive strand that is in actuality read backwards (thus the actual start of the read would be at `start` + `length` and proceed backwards to `start`).

If @glennhickey and @adamnovak agree with me that the first interpretation is the preferred one, I'll amend the documentation to make it official.

**Comment by glennhickey** [comment]
And the third would be like in MAF, where the start corresponds to position
_on the reverse strand_ (ie offset from end of sequence) when
strandIsForward = False...

Anyway, we're in agreement about what the correct meaning is, it just needs
to be explicitly written somewhere...

On Wed, Aug 19, 2015 at 3:52 PM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
@glennhickey that third interpretation is... wow, it's making my brain hurt. It didn't even occur to me. But yes, you're right, I'll make the first interpretation explicit.

**Comment by glennhickey** [comment]
MAF coordinates have certainly hurt my brain plenty over the years, but PSL
takes the cake for this.

http://www.genome.ucsc.edu/FAQ/FAQformat.html#format2

"Be aware that the coordinates for a negative strand in a PSL line are
handled in a special way. In the qStart and qEnd fields, the coordinates
indicate the position where the query matches from the point of view of the
forward strand, even when the match is on the reverse strand. However, in
the qStarts list, the coordinates are reversed."

and it goes downhill from there.

On Wed, Aug 19, 2015 at 4:02 PM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
I annotated the AllelePathItem SQL definition [here](https://github.com/macieksmuga/server/blob/graph/tests/data/graphs/graphSQL_v023.sql)

@glennhickey if you think this is sufficient, I'll issue a PR against it.

**Comment by glennhickey** [comment]
Sure, looks good. thanks!

On Fri, Aug 21, 2015 at 5:58 PM, Maciek Smuga-Otto <notifications@github.com
