### ISSUE TITLE
Discuss range radius query for visualization

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#152]

**Comment by macieksmuga** [comment]
The idea is to create a new subgraph query that instead of specifying a seed position + radius, specifies a coordinate range. This would be useful for incorporating graph displays into the genome browser.

**Comment by macieksmuga** [comment]
Since it's not clear we'll be going with the current SQL-backed sidegraph system in the future, I'll shelve this for now - but I _would_ like to talk with somebody who knows the genomics side of the story to gather the exact algorithmic requirements (ie. what does a coordinate mean for any given position on a graph? Where do I find the data to figure out this coordinate? What simplifying assumptions can I make?
